modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "floatingdamageindicators"
version = "${file.jarVersion}"
displayName = "Floating Damage Indicators"
authors = "3C Team"
description = '''
Adds floating damage numbers above every target you hit, and your own incoming damage too. Color-coded by damage type.
'''
logoFile = "assets/floatingdamageindicators/icon.png"

[[mixins]]
config = "floatingdamageindicators.mixins.json"
side = "CLIENT"

[[mixins]]
config = "floatingdamageindicators-server.mixins.json"
side = "SERVER"

[[dependencies.floatingdamageindicators]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.floatingdamageindicators]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"
